local module = {
	["M1"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
	["Sprint"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
	["Dash"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
	["Evasive"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
	["Skill1"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
	["Skill2"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
	["Skill3"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
	["Skill4"] = {
		OnCooldown = false,
		LastUsed = 0,
	},
}

return module
