local INPUTS = {
	["M1"] = {
		Name = "M1",
		Key = Enum.UserInputType.MouseButton1,
	},
	["Q"] = {
		Name = "Dash",
		Key = Enum.KeyCode.Q,
	},
	["1"] = {
		Name = "Action1",
		Key = Enum.KeyCode.One,
	},
	["2"] = {
		Name = "Action2",
		Key = Enum.KeyCode.Two,
	},
	["3"] = {
		Name = "Action3",
		Key = Enum.KeyCode.Three,
	},
	["4"] = {
		Name = "Action4",
		Key = Enum.KeyCode.Four,
	},
}

return INPUTS
